version: "3.9"

services:
  db:
    image: postgres:16
    container_name: location_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sbl_database
    ports:
      - "5432:5432"
